public class HelloWorld {
public static void main (String[]args) {
    System.out.println("Hello, World!");
}
}
public class AsciiChars {

    public static void main(String[] args) {
         public static void printNumbers() 
        for (int x = 0; x <128; x++) {
            System.out.println(x);
        }
//capital letters
{ public static void printUpperCase()
    for (int x = 65; x <91; x++) {
            System.out.print(x);
            System.out.prinlin("\t" + (char)x);
    }
}     
// lowercase
public static void printLowerCase()
            {for (int x = 97 x <123; x++) {
            System.out.print(x);
            System.out.prinlin("\t" + (char)x);
        }
        }
    }
}